name: Publish package to GitHub Packages
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@atlo-labs'
      - run: yarn install
      - run: yarn install --immutable
      - run: yarn build
      - uses: canastro/copy-file-action@master
        with:
          source: "package.json"
          target: "dist/package.json"
      - run: yarn publish dist
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}